import { chromium } from "@playwright/test";
const URL = process.env.U || "http://127.0.0.1:19995";
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 } });
await ctx.addInitScript(() => { if (!localStorage.getItem("ps5upload.host")) localStorage.setItem("ps5upload.host", "192.168.86.99"); });
const page = await ctx.newPage();
let navs = 0;
page.on("framenavigated", (f) => { if (f === page.mainFrame()) { navs++; console.log("NAV", navs, f.url()); } });
page.on("console", (m) => { if (/error|warn/i.test(m.type())) console.log("CONSOLE", m.type(), m.text().slice(0, 300)); });
page.on("pageerror", (e) => console.log("PAGEERROR", e.message));
page.on("requestfailed", (r) => console.log("REQFAILED", r.url(), r.failure()?.errorText));
page.on("response", (r) => { if (r.status() >= 400) console.log("HTTP", r.status(), r.url()); });
await page.route("**/api/pkg/install**", (r) => { console.log("INSTALL REQUEST", r.request().method(), r.request().url()); r.fulfill({ status: 500, body: "{}" }); });
await page.goto(`${URL}${process.env.P || "/install"}`);
await page.waitForTimeout(4000);
const main = page.locator("[data-scroll-root]:visible");
await main.getByRole("button", { name: "From this device" }).click();
await page.waitForTimeout(2000);
await page.screenshot({ path: "/tmp/claude-501/i418-2.png" });
const dlg = page.getByRole("dialog");
console.log("DIALOG:", (await dlg.innerText().catch(() => "(no dialog)")).slice(0, 600));
// The engine runs on this Mac: the picker browses this Mac's disk.
const pathBox = dlg.getByRole("textbox").first();
await pathBox.fill(process.env.HOME + "/ps5upload-i418-test").catch(() => {});
await pathBox.press("Enter").catch(() => {});
await page.waitForTimeout(1500);
await dlg.getByText("umtx2.github.pkg").first().click().catch((e) => console.log("no pkg", e.message.slice(0, 80)));
await page.waitForTimeout(500);
await page.screenshot({ path: "/tmp/claude-501/i418-3.png" });
const pickBtns = await dlg.getByRole("button").allInnerTexts().catch(() => []);
console.log("DIALOG BUTTONS:", pickBtns);

await b.close();
