/* P3 Task 7: the hardware / system / accounts / cheats / mods / notices / Remote Play methods
 * driven through the real dispatcher (payload/src/mgmt_rpc.c) and the REAL rows of
 * payload/src/mgmt_table.def.
 *
 * build.rs copies the rows between the "P3 Task 7" markers of mgmt_table.def into
 * $OUT_DIR/t7_rows.def; this file expands them with stub handlers in place of runtime.c's (which is
 * only built by the SDK). So a row added to, changed in or dropped from the real table changes what
 * these tests cover: the method number, the legacy frames, the MGMT_SONY flag and the runner are the
 * real ones; only the handler body is a stub.
 *
 * The Sony-flagged stubs take the REAL sony_api_lock (payload/src/sony_api_lock.c) around a 15 ms
 * "Sony call", exactly as the real handlers take it, and count how many threads are inside at once.
 */
#include <pthread.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "ava1_gen.h"
#include "mgmt_rpc.h"
#include "sony_api_lock.h"

#include "t7_frames.h" /* generated by build.rs from runtime.c */

/* The frame numbers the rows name (runtime.c's MGMT_FRAME_* macros); the host knows only the number
 * a row maps to, so the rows are read with a catch-all macro for the constants. */
static int g_in, g_peak;
static pthread_mutex_t g_stat = PTHREAD_MUTEX_INITIALIZER;

static void sony_enter(void) {
    pthread_mutex_lock(&sony_api_lock);
    pthread_mutex_lock(&g_stat);
    if (++g_in > g_peak) g_peak = g_in;
    pthread_mutex_unlock(&g_stat);
}
static void sony_leave(void) {
    pthread_mutex_lock(&g_stat);
    g_in--;
    pthread_mutex_unlock(&g_stat);
    pthread_mutex_unlock(&sony_api_lock);
}

static int send_(uint16_t type, const char *body) {
    return mgmt_capture_active() ? mgmt_capture_frame(type, body, strlen(body)) : -1;
}

static int t7_stub(uint64_t method, int sony, uint16_t ack, const char *b, uint64_t l) {
    char out[512];
    char shown[200];
    size_t i, n = 0;
    if (sony) {
        sony_enter();
        usleep(15 * 1000);
        sony_leave();
    }
    if (strstr(b, "@ERRFRAME")) return mgmt_capture_active() ? mgmt_capture_frame(MGMT_FRAME_ERROR, "body_too_large", 14) : -1;
    if (strstr(b, "@FAILFIRST")) return send_(ack, "{\"ok\":false,\"code\":7,\"err\":\"bad_thing\"}");
    if (strstr(b, "@FAILLATE")) return send_(ack, "{\"err\":\"bad_thing\",\"code\":7,\"ok\":false}");
    if (strstr(b, "@TWO")) {
        send_(ack, "{\"progress\":50}");
        return send_(ack, "{\"done\":true}");
    }
    for (i = 0; i < l && n + 1 < sizeof shown; i++) shown[n++] = (b[i] == '"' || b[i] == '\\' || (unsigned char)b[i] < 0x20) ? '\'' : b[i];
    shown[n] = '\0';
    snprintf(out, sizeof out, "{\"m\":%llu,\"n\":%llu,\"b\":\"%s\"}", (unsigned long long)method, (unsigned long long)l, shown);
    return send_(ack, out);
}

#define STUB_FN(m, f, a, fl, h, runner)                                                                    \
    static int stub_##m(void *st, int fd, uint64_t t, const char *b, uint64_t l) {                          \
        (void)st;                                                                                          \
        (void)fd;                                                                                          \
        (void)t;                                                                                           \
        return t7_stub((m), ((fl) & MGMT_SONY) != 0, (uint16_t)(a), b, l);                                  \
    }                                                                                                      \
    static int run_##m(const uint8_t *q, uint32_t n, mgmt_ctx_t *cx) { return runner(q, n, cx, stub_##m); }
#define MGMT_H0 STUB_FN
#define MGMT_H1 STUB_FN
#include "t7_rows.def"
#undef MGMT_H0
#undef MGMT_H1

#define ROW(m, f, a, fl, h, runner) {(uint16_t)(m), (uint16_t)(f), (uint16_t)(a), (fl), run_##m},
#define MGMT_H0 ROW
#define MGMT_H1 ROW
static const mgmt_entry_t k_t7[] = {
#include "t7_rows.def"
};
#undef MGMT_H0
#undef MGMT_H1

int ava1_test_t7_install(void) {
    g_in = g_peak = 0;
    return mgmt_rpc_install(k_t7, sizeof k_t7 / sizeof k_t7[0], NULL, NULL, NULL);
}
size_t ava1_test_t7_count(void) { return sizeof k_t7 / sizeof k_t7[0]; }
int ava1_test_t7_entry(size_t i, uint32_t *method, uint32_t *flags, uint32_t *frame, uint32_t *ack) {
    if (i >= sizeof k_t7 / sizeof k_t7[0]) return -1;
    *method = k_t7[i].method;
    *flags = k_t7[i].flags;
    *frame = k_t7[i].legacy_frame;
    *ack = k_t7[i].ack_frame;
    return 0;
}
int ava1_test_t7_sony_peak(void) {
    int p;
    pthread_mutex_lock(&g_stat);
    p = g_peak;
    pthread_mutex_unlock(&g_stat);
    return p;
}
void ava1_test_t7_reset_peak(void) {
    pthread_mutex_lock(&g_stat);
    g_peak = g_in;
    pthread_mutex_unlock(&g_stat);
}
