[package]
name = "ps5upload-lab"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
serde.workspace = true
serde_json.workspace = true
flate2 = "1"
ps5upload-core = { path = "../ps5upload-core" }
ava1 = { path = "../ava1" }
ava1-chaos = { path = "../ava1-chaos" }
ps5upload-ava1 = { path = "../ps5upload-ava1" }
tokio = { workspace = true, features = ["net", "time", "io-util", "rt-multi-thread", "macros", "io-std"] }
uuid.workspace = true
