#!/usr/bin/env bash
#
# Post-`tauri android init` patches for the Android build. `gen/android`
# is gitignored and regenerated by `tauri android init`, so these MUST
# run AFTER init and BEFORE `tauri android build`. Idempotent. Invoked
# from publish.yml, engine-ci.yml, and the Makefile `android-init` target.
#
# Two patches:
#
# 1) Loopback cleartext for the in-process engine.
#    The mobile build links ps5upload-engine in-process and binds it to
#    http://127.0.0.1:19113; the renderer fetches that URL like the
#    desktop sidecar (engine_mobile.rs + client/src/api/engine.ts). Tauri
#    sets android:usesCleartextTraffic=true for debug but FALSE for
#    release, so a release APK silently blocks the loopback fetch and the
#    UI shows the engine "red". We add a network-security-config that
#    permits cleartext ONLY for 127.0.0.1 / localhost; everything else
#    stays cleartext-forbidden. networkSecurityConfig takes precedence
#    over the usesCleartextTraffic flag for those domains.
#
# 2) Explicit backup rules so user settings survive an uninstall/reinstall
#    (cloud backup / device transfer). Settings already persist across
#    normal restarts (app-private config dir) and in-place updates (now
#    that releases share a stable signing key), but allowBackup + explicit
#    include rules let Android restore them on a fresh reinstall too.
#
# Plus <uses-permission> injection: all-files storage access for the
# in-app picker, and Wi-Fi multicast/state permissions so mDNS console
# discovery can receive 224.0.0.251:5353 (see the perms list below).
# The MulticastLock itself is acquired via JNI at runtime — see
# local_fs.rs::acquire_multicast_lock, called from discover_ps5.
#
# 3) Pin WebView textZoom to 100% in MainActivity. Android WebView scales
#    every font by the device's system **Font size** accessibility setting,
#    so a user with a larger-than-default font sees text blown up — dense rows
#    (Library, Upload) clip to the first few characters. Overriding the
#    onWebViewCreate hook (exposed by WryActivity) to set textZoom = 100 makes
#    the app render at its designed size regardless of that setting.
#
#    NOTE: textZoom only counters **Font size**, NOT **Display size**. Display
#    size changes the WebView's density and scales the WHOLE viewport (icons,
#    padding, controls — not just text), which textZoom can't touch. That case
#    is handled in-app by the user-adjustable "Text size" setting
#    (client/src/state/uiScale.ts), which rescales the rem root and so resizes
#    the entire UI. The two fixes are complementary.

set -euo pipefail

root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
gen="$root/client/src-tauri/gen/android/app/src/main"
manifest="$gen/AndroidManifest.xml"
xmldir="$gen/res/xml"

if [ ! -f "$manifest" ]; then
  echo "::error::AndroidManifest.xml not found at $manifest — run 'tauri android init' first" >&2
  exit 1
fi

mkdir -p "$xmldir"

# --- (1) loopback-only cleartext --------------------------------------
cat >"$xmldir/network_security_config.xml" <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<!-- Loopback-only cleartext: the in-process ps5upload-engine binds
     127.0.0.1:19113 and the WebView fetches it over plain HTTP. All
     other traffic stays cleartext-forbidden. -->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">localhost</domain>
    </domain-config>
</network-security-config>
XML
echo "wrote $xmldir/network_security_config.xml"

# --- (2) backup rules -------------------------------------------------
# Android 12+ uses dataExtractionRules; older uses fullBackupContent.
# Include the whole app files domain (where settings.json lives) for both
# cloud backup and device-to-device transfer.
cat >"$xmldir/data_extraction_rules.xml" <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<data-extraction-rules>
    <cloud-backup>
        <include domain="file" path="." />
    </cloud-backup>
    <device-transfer>
        <include domain="file" path="." />
    </device-transfer>
</data-extraction-rules>
XML
echo "wrote $xmldir/data_extraction_rules.xml"

cat >"$xmldir/backup_rules.xml" <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<full-backup-content>
    <include domain="file" path="." />
</full-backup-content>
XML
echo "wrote $xmldir/backup_rules.xml"

# --- patch <application> attributes, idempotently ---------------------
python3 - "$manifest" <<'PY'
import re, sys
path = sys.argv[1]
src = open(path, encoding="utf-8").read()

wanted = {
    "android:networkSecurityConfig": "@xml/network_security_config",
    "android:allowBackup": "true",
    "android:fullBackupContent": "@xml/backup_rules",
    "android:dataExtractionRules": "@xml/data_extraction_rules",
}
inject = "".join(
    f' {k}="{v}"' for k, v in wanted.items() if k not in src
)
if inject:
    new = re.sub(r"(<application\b)", r"\1" + inject, src, count=1)
    if new == src:
        sys.exit("::error::could not find <application> tag to patch")
    src = new
    print("patched <application> with:" + inject)
else:
    print("<application> already patched — skipping")

# All-files storage access so the in-app file/folder picker can read
# arbitrary game folders / .zips under /storage (the engine walks real FS
# paths; SAF content:// URIs are unusable). MANAGE_EXTERNAL_STORAGE is the
# API 30+ permission; the legacy READ/WRITE_EXTERNAL_STORAGE (maxSdk 29)
# cover older devices. Inserted before </application>'s closing, just
# after the opening <application ...> line, idempotently.
perms = [
    '<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />',
    '<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" />',
    '<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29" />',
    # mDNS console discovery: receiving multicast (224.0.0.251:5353)
    # requires CHANGE_WIFI_MULTICAST_STATE; without it the Wi-Fi stack
    # filters multicast frames and discovery silently finds nothing.
    # ACCESS_NETWORK_STATE / ACCESS_WIFI_STATE let the engine pick the
    # right interface. The MulticastLock is acquired at runtime via JNI
    # (see local_fs.rs::acquire_multicast_lock, called from discover_ps5).
    '<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />',
    '<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />',
    '<uses-permission android:name="android.permission.CHANGE_WIFI_MULTICAST_STATE" />',
]
missing = [p for p in perms if 'android.permission.' + p.split('android.permission.')[1].split('"')[0] not in src]
if missing:
    block = "\n    " + "\n    ".join(missing)
    new = re.sub(r"(<manifest\b[^>]*>)", r"\1" + block, src, count=1)
    if new == src:
        sys.exit("::error::could not find <manifest> tag to add permissions")
    src = new
    print("added permissions:", ", ".join(p.split('"')[1] for p in missing))
else:
    print("permissions already present — skipping")

open(path, "w", encoding="utf-8").write(src)
PY

# --- (3) pin WebView textZoom in MainActivity ------------------------
# MainActivity.kt is the user-owned activity (not under generated/); we add
# an onWebViewCreate override that pins textZoom so the device font-scale
# doesn't enlarge the UI. Idempotent: skipped if the override already exists.
mainactivity="$(find "$gen/java" -name MainActivity.kt -print -quit 2>/dev/null || true)"
if [ -z "$mainactivity" ]; then
  echo "::warning::MainActivity.kt not found under $gen/java — skipping textZoom patch" >&2
else
  python3 - "$mainactivity" <<'PY'
import sys
path = sys.argv[1]
src = open(path, encoding="utf-8").read()
if "onWebViewCreate" in src:
    print("MainActivity.kt already has onWebViewCreate — skipping")
    sys.exit(0)
method = '''
  // Pin WebView text zoom to 100% so the UI renders at its designed 18px base
  // regardless of the device's system Font size / Display size accessibility
  // setting (Android WebView otherwise multiplies every font by it, which on a
  // larger-than-default font overflows the dense rem-based layout and clips
  // e.g. Library/Upload rows to "PPS..."). textZoom affects only text size,
  // not pinch-zoom.
  override fun onWebViewCreate(webView: android.webkit.WebView) {
    webView.settings.textZoom = 100
    super.onWebViewCreate(webView)
  }
'''
idx = src.rstrip().rfind("}")
if idx == -1:
    sys.exit("::error::could not find class closing brace in MainActivity.kt")
src = src[:idx] + method + src[idx:]
open(path, "w", encoding="utf-8").write(src)
print("patched MainActivity.kt with onWebViewCreate textZoom=100")
PY
fi

echo "android post-init patches applied"
