#include "remoteplay.h"

#include <ps5/kernel.h>

#include <dlfcn.h>
#include <pthread.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#include "notif.h"
#include "proc_list.h"
#include "sony_api_lock.h"
#include "sys_registry.h"
#include "rp_keys.h"
#include "fw_spoof.h"

/* Forward declaration: rp_enable_locked calls this before it is
 * defined. See the serialization note at the bottom of this file for
 * why the cores must call each other rather than the public wrappers. */
static int rp_readiness_json_locked(char *out, size_t out_size);

#define RP_STATE_IDLE      0
#define RP_STATE_STARTING  1
#define RP_STATE_WAITING   2
#define RP_STATE_PAIRED    3
#define RP_STATE_FAILED    4
#define RP_STATE_TIMEOUT   5

#define RP_WAIT_SECONDS    300

/* Registry key for the Remote Play enable flag. When this is 0, PINs
 * generated by sceRemoteplayGeneratePinCode are unusable — the PSN
 * pairing handshake silently fails because the service is off. elf-arsenal
 * force-sets it to 1 before generating a PIN; we do the same. */
#define SCE_REGMGR_ENT_KEY_REMOTEPLAY_rp_enable 1098973184u

/* libSceUserService — already link-time bound (-lSceUserService in the
 * Makefile) so a plain extern declaration is enough; dlsym(RTLD_DEFAULT)
 * resolves it at runtime. Same pattern as runtime.c line 9516. */
extern int sceUserServiceGetForegroundUser(int *user_id);
/* Must be called before any other user-service query, or
 * GetForegroundUser fails 0x80960002 even with a user logged in. Other
 * call sites in this tree already do it; Remote Play did not, which is
 * why it could never see the signed-in user. Idempotent. */
extern int sceUserServiceInitialize(void *params);

/* Idempotent wrapper so every entry point into this file is safe to call
 * without knowing whether something else initialised the service. */
static void rp_user_service_ready(void) {
    static int done = 0;
    if (done) return;
    (void)sceUserServiceInitialize(NULL);
    done = 1;
}

/* libSceRemoteplay function pointer types. The library is NOT link-time
 * bound (it's an optional SPRX; adding a DT_NEEDED entry would brick the
 * payload on firmwares where the module is absent), so we dlopen it once
 * and dlsym each symbol. NULL after resolve means "not available on this
 * firmware" — callers surface a clean error instead of crashing. */
/* Arity confirmed against three independent implementations (linkdev,
 * ps5-remoteplay-get-pin, ActRemoteLink) and verified on hardware: the
 * previous `(void)` declaration made every call fail 0x80FC0001, because
 * the callee read whatever happened to be in the argument registers.
 * That is why Remote Play never worked. */
typedef int (*rp_init_fn)(void *opt, size_t opt_size);
typedef int (*rp_get_op_status_fn)(int32_t user_id);
typedef int (*rp_get_conn_status_fn)(void);
/* Writes the PIN through its ONLY argument. The previous
 * `(user_id, char*, size_t)` form passed an integer where the callee
 * performs a pointer store — a wild write, not a PIN. */
typedef int (*rp_gen_pin_fn)(uint32_t *out_pin);
typedef int (*rp_is_playing_fn)(void);
typedef int (*rp_get_mode_fn)(void);
typedef int (*rp_disconnect_fn)(void);
/* ConfirmDeviceRegist reports the authoritative pairing outcome:
 *   status 2 = paired, 3/4 = failed (with errcode for diagnostics).
 * NotifyPinCodeError clears stale PIN-error state from a prior session. */
typedef int (*rp_confirm_regist_fn)(uint32_t *status, uint32_t *errcode);
typedef int (*rp_notify_pin_err_fn)(int errcode);

static rp_init_fn           g_init         = NULL;
static rp_get_conn_status_fn g_conn_status = NULL;
static rp_gen_pin_fn        g_gen_pin      = NULL;
static rp_is_playing_fn     g_is_playing   = NULL;
static rp_disconnect_fn     g_disconnect   = NULL;
static rp_confirm_regist_fn g_confirm_regist = NULL;
static rp_notify_pin_err_fn g_notify_pin_err = NULL;

static pthread_once_t g_resolve_once = PTHREAD_ONCE_INIT;
static int g_resolved = 0;

static void resolve_impl(void) {
    /* libSceRemoteplay.sprx may live in several system paths depending
     * on firmware. Try each and stop at the first dlopen success, same
     * strategy as bgft.c's libSceBgft lookup. RTLD_GLOBAL so the symbols
     * are visible to subsequent dlsym(RTLD_DEFAULT) if needed. */
    static const char *const RP_LIB_PATHS[] = {
        "/system/common/lib/libSceRemoteplay.sprx",
        "/system_ex/common/lib/libSceRemoteplay.sprx",
        "/system/priv/lib/libSceRemoteplay.sprx",
    };
    void *lib = NULL;
    for (size_t i = 0; i < sizeof(RP_LIB_PATHS) / sizeof(RP_LIB_PATHS[0]); i++) {
        lib = dlopen(RP_LIB_PATHS[i], RTLD_NOW | RTLD_GLOBAL);
        if (lib) break;
    }
    if (!lib) {
        /* Fall back to RTLD_DEFAULT in case another process already
         * pulled the module into our address space. */
        lib = RTLD_DEFAULT;
    }
    g_init       = (rp_init_fn)dlsym(lib, "sceRemoteplayInitialize");
    g_conn_status= (rp_get_conn_status_fn)dlsym(lib, "sceRemoteplayGetConnectionStatus");
    g_gen_pin    = (rp_gen_pin_fn)dlsym(lib, "sceRemoteplayGeneratePinCode");
    g_is_playing = (rp_is_playing_fn)dlsym(lib, "sceRemoteplayIsRemotePlaying");
    g_disconnect = (rp_disconnect_fn)dlsym(lib, "sceRemoteplayDisconnect");
    g_confirm_regist = (rp_confirm_regist_fn)dlsym(lib, "sceRemoteplayConfirmDeviceRegist");
    g_notify_pin_err = (rp_notify_pin_err_fn)dlsym(lib, "sceRemoteplayNotifyPinCodeError");
    g_resolved = 1;
}

static void resolve_once(void) {
    pthread_once(&g_resolve_once, resolve_impl);
}

/* ── Account ID auto-detect via the registry ──────────────────────────
 *
 * Chiaki/pxplay need the console's PSN account ID (base64 of the 8-byte
 * raw id) in addition to the pairing PIN. Sony buries it; we read it
 * straight from the registry for the foreground user. Ported from
 * elf-arsenal's remoteplay.c, adapted to ps5upload's sys_registry
 * wrappers (dlsym'd sceRegMgr, read-only — no writes to the registry).
 *
 * The key IDs are computed with Sony's regmgr entry-number formula:
 * (slot-1)*stride + base, with a per-namespace base for the user-id and
 * account-id slot tables. These bases match ps5-payload-dev/regdump. */
static uint32_t rp_regmgr_ent_num(uint32_t slot, uint32_t max,
                                  uint32_t stride, uint32_t base,
                                  uint32_t fallback) {
    if (slot < 1 || slot > max) return fallback;
    return (slot - 1) * stride + base;
}

static uint32_t rp_key_user_id(uint32_t slot) {
    return rp_regmgr_ent_num(slot, 16, 65536, 125829376, 127140096);
}

static uint32_t rp_key_account_id(uint32_t slot) {
    return rp_regmgr_ent_num(slot, 16, 65536, 125830400, 127141120);
}

static const char rp_b64tab[] =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/* Standard base64 with '=' padding. Note: the elf-arsenal reference this
 * was ported from has a padding bug — its `i > inlen` guards can never
 * fire (i is capped at inlen by the read guards), so it emits trailing
 * 'A's instead of '=' and an 8-byte account id came out as
 * "…d4gA" instead of the correct "…d4g=". We drive padding off the
 * remaining-byte count of each group instead, which pads correctly for
 * all lengths (verified against RFC 4648 test vectors). */
static void rp_base64_encode(const uint8_t *in, size_t inlen, char *out) {
    size_t i = 0, j = 0;
    while (i < inlen) {
        size_t rem = inlen - i; /* bytes left in this group: 1, 2, or 3 */
        uint32_t o0 = in[i];
        uint32_t o1 = rem > 1 ? in[i + 1] : 0;
        uint32_t o2 = rem > 2 ? in[i + 2] : 0;
        uint32_t v = (o0 << 16) | (o1 << 8) | o2;
        out[j++] = rp_b64tab[(v >> 18) & 63];
        out[j++] = rp_b64tab[(v >> 12) & 63];
        out[j++] = rem > 1 ? rp_b64tab[(v >> 6) & 63] : '=';
        out[j++] = rem > 2 ? rp_b64tab[(v) & 63] : '=';
        i += 3;
    }
    out[j] = '\0';
}

/* Fill `out` with the foreground user's base64 account id, or leave it
 * an empty string if it can't be resolved (no user logged in, registry
 * symbols unavailable on this firmware, etc.). Never fails hard — a
 * missing account id just means the UI shows only the PIN. */
/* Registry slot (1..16) whose user-id matches `uid`, or -1.
 *
 * The slot is the index every per-user key is derived from, so almost
 * everything below needs it. */
static int rp_slot_for_user(int uid) {
    if (uid <= 0) return -1;
    for (uint32_t i = 1; i <= 16; i++) {
        int reg_uid = 0;
        if (sys_registry_get_int(rp_key_user_id(i), &reg_uid, NULL) == 0 &&
            reg_uid == uid) {
            return (int)i;
        }
    }
    return -1;
}

static void rp_get_account_id(char *out, size_t out_sz) {
    if (!out || out_sz == 0) return;
    out[0] = '\0';

    int uid = 0;
    rp_user_service_ready();
    if (sceUserServiceGetForegroundUser(&uid) != 0 || uid <= 0) return;

    int slot = rp_slot_for_user(uid);
    if (slot < 0) return;

    uint8_t raw[8] = {0};
    if (sys_registry_get_bin(rp_key_account_id((uint32_t)slot), raw,
                             sizeof(raw), NULL) != 0) {
        return;
    }

    char b64[16];
    rp_base64_encode(raw, sizeof(raw), b64);
    snprintf(out, out_sz, "%s", b64);
}

/* Enumerate the 32-slot registration table — the devices this console
 * has been paired with.
 *
 * A slot whose user_id reads 0 is empty. regist_key and aes_key are
 * deliberately NOT reported: they are pairing secrets, nothing in the UI
 * needs them, and they should not travel over the wire. */
static int rp_devices_json_locked(char *out, size_t out_size) {
    size_t n = 0;
    int first = 1;

    n += (size_t)snprintf(out + n, out_size - n, "{\"devices\":[");
    for (uint32_t slot = 1; slot <= 32; slot++) {
        int user_id = 0;
        int client_type = 0;
        uint32_t ec = 0;
        if (sys_registry_get_int(rp_key_regist_user_id(slot), &user_id, &ec) != 0) {
            continue;
        }
        if (user_id == 0 || user_id == -1) continue;
        (void)sys_registry_get_int(rp_key_regist_client_type(slot),
                                   &client_type, NULL);
        /* Leave room for the closing "]}" plus a NUL. */
        if (n + 80 >= out_size) break;
        n += (size_t)snprintf(out + n, out_size - n,
                              "%s{\"slot\":%u,\"user_id\":%d,\"client_type\":%d}",
                              first ? "" : ",", slot, user_id, client_type);
        first = 0;
    }
    n += (size_t)snprintf(out + n, out_size - n, "]}");
    return (int)n;
}

/* Turn Remote Play on.
 *
 * Two scopes, because FW 10.00 split them: the system-wide service
 * toggle, and per-user permission ("select which users can access your
 * console"). A console can have the service on while the account being
 * used is not permitted — pairing succeeds and every session is refused.
 *
 * Returns the re-read readiness snapshot rather than a bare ok, so the
 * caller never has to assume the write stuck.
 *
 * Return: >=0 length written, -1 write failed, -2 firmware has no
 * per-user setting, -3 no foreground user to apply it to. */
static int rp_enable_locked(int user_scope, char *out, size_t out_size) {
    unsigned int fw = fw_safe_kernel_version();

    if (!user_scope) {
        uint32_t ec = 0;
        if (sys_registry_set_int(rp_key_service_enable(), 1, &ec) != 0) {
            return -1;
        }
    } else {
        /* Refuse rather than write a key that may not exist on this
         * firmware. rp_fw_has_per_user_enable() also returns 0 when the
         * version could not be read at all, so an unidentified console
         * fails closed. */
        if (!rp_fw_has_per_user_enable(fw)) return -2;

        int uid = 0;
        rp_user_service_ready();
        if (sceUserServiceGetForegroundUser(&uid) != 0 || uid <= 0) return -3;
        int slot = rp_slot_for_user(uid);
        if (slot < 1) return -3;

        uint32_t ec = 0;
        if (sys_registry_set_int(rp_key_user_enable((uint32_t)slot), 1, &ec) != 0) {
            return -1;
        }
    }
    return rp_readiness_json_locked(out, out_size);
}

static void rp_json_escape(const char *src, char *dst, size_t dst_cap);

/* Read-only snapshot of everything that decides whether Remote Play can
 * work on this console, right now.
 *
 * Deliberately performs NO writes. The point is that the UI can tell
 * someone exactly which precondition is missing instead of surfacing a
 * Sony error code, and every fix is then a separate, explicit action.
 *
 * The two gates people trip over: the service toggle, and — on FW 10.00
 * and later — per-user permission. Pairing can succeed while sessions are
 * refused because the second is unset. */
static int rp_readiness_json_locked(char *out, size_t out_size) {
    /* Resolve first, or symbols_ok would report "unavailable" merely
     * because nothing has asked for them yet. Resolution is idempotent
     * and cheap; reporting a stale false is a lie the UI would repeat. */
    resolve_once();

    int uid = 0;
    int svc = 0;
    int usr = 0;
    unsigned int fw = fw_safe_kernel_version();
    int has_per_user = rp_fw_has_per_user_enable(fw);
    uint64_t acct_raw = 0;
    char acct_b64[32] = "";
    char acct_type[24] = "";
    char acct_type_esc[64] = "";

    rp_user_service_ready();
    if (sceUserServiceGetForegroundUser(&uid) != 0) uid = 0;
    int slot = rp_slot_for_user(uid);

    if (slot > 0) {
        uint8_t raw[8] = {0};
        if (sys_registry_get_bin(rp_key_account_id((uint32_t)slot), raw,
                                 sizeof(raw), NULL) == 0) {
            /* Little-endian: the account id is the raw 8 bytes, and the
             * base64 clients want is over those bytes, not over a hex
             * rendering of them. */
            for (int i = 7; i >= 0; i--) {
                acct_raw = (acct_raw << 8) | raw[i];
            }
            rp_base64_encode(raw, sizeof(raw), acct_b64);
        }
        (void)sys_registry_get_str(rp_key_account_type((uint32_t)slot),
                                   acct_type, sizeof(acct_type), NULL);
    }

    /* Keep the registry error code. Passing NULL here is how a TOTAL
     * registry failure hid for so long: every read returned 0 and the
     * snapshot reported a perfectly plausible "nothing is enabled",
     * when in truth no read had succeeded at all. A non-zero
     * registry_err means "could not read", not "disabled". */
    uint32_t svc_ec = 0;
    (void)sys_registry_get_int(rp_key_service_enable(), &svc, &svc_ec);
    if (slot > 0 && has_per_user) {
        (void)sys_registry_get_int(rp_key_user_enable((uint32_t)slot), &usr,
                                   NULL);
    }

    rp_json_escape(acct_type, acct_type_esc, sizeof(acct_type_esc));

    return snprintf(out, out_size,
                    "{\"fw_magic\":%u,\"has_per_user\":%d,"
                    "\"foreground_uid\":%d,\"user_slot\":%d,"
                    "\"account_id_b64\":\"%s\",\"account_id_raw\":%llu,"
                    "\"account_type\":\"%s\",\"service_enabled\":%d,"
                    "\"user_enabled\":%d,\"symbols_ok\":%d,\"registry_err\":%u}",
                    fw, has_per_user, uid, slot, acct_b64,
                    (unsigned long long)acct_raw, acct_type_esc,
                    svc ? 1 : 0, usr ? 1 : 0, g_resolved ? 1 : 0, svc_ec);
}

static void rp_json_escape(const char *src, char *dst, size_t dst_cap) {
    if (!src || !dst || dst_cap == 0) return;
    size_t i = 0;
    while (*src && i + 2 < dst_cap) {
        char c = *src++;
        if (c == '"' || c == '\\') {
            dst[i++] = '\\';
            dst[i++] = c;
        } else if (c == '\n') {
            dst[i++] = '\\';
            dst[i++] = 'n';
        } else if ((unsigned char)c < 0x20) {
            continue;
        } else {
            dst[i++] = c;
        }
    }
    dst[i] = 0;
}

static pthread_mutex_t g_rp_mtx = PTHREAD_MUTEX_INITIALIZER;
static int g_rp_state = RP_STATE_IDLE;
static char g_rp_err[128] = "";
static char g_rp_pin[16] = "";
static char g_rp_account_id[32] = "";
static time_t g_rp_deadline = 0;

/* Clear stale Remote Play pairing state.
 *
 * This used to find the SceRemotePlay system daemon and proc_kill() it,
 * then wait up to 6.5s for the OS to respawn it. That is the same hazard
 * as SIGKILLing SceShellUI (see ptrace_recovery.h): killing a Sony system
 * process to "reset" it can wedge the whole console, and it did — a PS5
 * Pro on FW 9.60 froze on a pairing request and needed a hard reboot.
 *
 * Sony provides the supported way to do this: sceRemoteplayNotifyPinCodeError(1)
 * clears stale PIN state, which is what the reference implementations use
 * and what the caller already invokes. Nothing here needs to kill anything.
 */
static void rp_reset_daemon(void) {
    /* Intentionally empty. See the comment above: the daemon must not be
     * killed. Kept as a named no-op so the call site still reads as
     * "clear stale state" and nobody reintroduces the kill. */
}

/* ── Auto-enable Remote Play in registry ────────────────────────────
 *
 * If the rp_enable registry key is 0 (Remote Play disabled in System
 * Settings), the PIN we generate is unusable. Force it to 1 so the
 * pairing handshake succeeds. Best-effort — a registry write failure
 * is logged but doesn't block the PIN flow (some firmwares may reject
 * the write or have already enabled it). */
static void rp_ensure_enabled(void) {
    int enabled = 0;
    if (sys_registry_get_int(SCE_REGMGR_ENT_KEY_REMOTEPLAY_rp_enable,
                             &enabled, NULL) == 0 && enabled != 1) {
        sys_registry_set_int(SCE_REGMGR_ENT_KEY_REMOTEPLAY_rp_enable,
                             1, NULL);
    }
}

static const char *state_name(int s) {
    switch (s) {
        case RP_STATE_IDLE: return "idle";
        case RP_STATE_STARTING: return "starting";
        case RP_STATE_WAITING: return "waiting";
        case RP_STATE_PAIRED: return "paired";
        case RP_STATE_FAILED: return "failed";
        case RP_STATE_TIMEOUT: return "timeout";
        default: return "unknown";
    }
}

void remoteplay_init(void) {
    pthread_mutex_lock(&g_rp_mtx);
    g_rp_state = RP_STATE_IDLE;
    g_rp_err[0] = 0;
    g_rp_pin[0] = 0;
    g_rp_account_id[0] = 0;
    g_rp_deadline = 0;
    pthread_mutex_unlock(&g_rp_mtx);
}

static int rp_request_locked(const char *manual_account_id) {
    resolve_once();

    /* Resolve the account id before taking the lock — it does registry +
     * user-service IPC we don't want to hold g_rp_mtx across (status
     * polls contend on it). A caller-supplied id wins; otherwise
     * auto-detect the foreground user's so the UI can show what Chiaki/
     * pxplay need without the user hunting it down. */
    char account_id[sizeof(g_rp_account_id)] = "";
    if (manual_account_id && manual_account_id[0]) {
        snprintf(account_id, sizeof(account_id), "%s", manual_account_id);
    } else {
        rp_get_account_id(account_id, sizeof(account_id));
    }

    pthread_mutex_lock(&g_rp_mtx);
    g_rp_pin[0] = 0;
    snprintf(g_rp_account_id, sizeof(g_rp_account_id), "%s", account_id);
    g_rp_err[0] = 0;
    g_rp_deadline = 0;
    if (!g_resolved) {
        g_rp_state = RP_STATE_FAILED;
        snprintf(g_rp_err, sizeof(g_rp_err), "remoteplay symbols not resolved");
        pthread_mutex_unlock(&g_rp_mtx);
        return -1;
    }
    if (!g_init || !g_gen_pin) {
        g_rp_state = RP_STATE_FAILED;
        snprintf(g_rp_err, sizeof(g_rp_err), "sceRemoteplayInitialize/GeneratePinCode unavailable");
        pthread_mutex_unlock(&g_rp_mtx);
        return -1;
    }

    g_rp_state = RP_STATE_STARTING;
    pthread_mutex_unlock(&g_rp_mtx);

    /* Clear stale Remote Play daemon state before initializing. Without
     * this, a prior failed pairing attempt can leave the IPC channel in
     * a bad state, causing Initialize or GeneratePinCode to fail. */
    rp_reset_daemon();

    /* Ensure Remote Play is enabled in system settings — if the user
     * never toggled Settings → System → Remote Play, the PIN would be
     * unusable. Force the registry key on before we proceed. */
    rp_ensure_enabled();

    /* Clear stale PIN-error state from any prior session. */
    if (g_notify_pin_err) (void)g_notify_pin_err(1);

    /* Initialize the Remoteplay module. Sony's init is idempotent — a
     * second call returns a benign "already initialised" code which we
     * treat as success. */
    int rc = g_init(0, 0);
    if (rc != 0) {
        pthread_mutex_lock(&g_rp_mtx);
        g_rp_state = RP_STATE_FAILED;
        snprintf(g_rp_err, sizeof(g_rp_err),
                 "sceRemoteplayInitialize failed: 0x%08X", (unsigned)rc);
        pthread_mutex_unlock(&g_rp_mtx);
        return -1;
    }

    /* Get the foreground user id. sceUserServiceGetForegroundUser is
     * link-time bound via -lSceUserService, so the extern declaration
     * above resolves directly. A uid <= 0 means no user is logged in. */
    int uid = 0;
    rp_user_service_ready();
    rc = sceUserServiceGetForegroundUser(&uid);
    if (rc != 0 || uid <= 0) {
        pthread_mutex_lock(&g_rp_mtx);
        g_rp_state = RP_STATE_FAILED;
        snprintf(g_rp_err, sizeof(g_rp_err),
                 "no foreground user (rc=0x%08X uid=%d)", (unsigned)rc, uid);
        pthread_mutex_unlock(&g_rp_mtx);
        return -1;
    }

    /* Generate the pairing PIN. The caller enters this in the Remote
     * Play client to pair with this console. */
    uint32_t pin_raw = 0;
    rc = g_gen_pin(&pin_raw);
    char pin[16];
    snprintf(pin, sizeof(pin), "%08u", (unsigned)pin_raw);
    if (rc != 0) {
        pthread_mutex_lock(&g_rp_mtx);
        g_rp_state = RP_STATE_FAILED;
        snprintf(g_rp_err, sizeof(g_rp_err),
                 "sceRemoteplayGeneratePinCode failed: 0x%08X", (unsigned)rc);
        pthread_mutex_unlock(&g_rp_mtx);
        return -1;
    }

    pthread_mutex_lock(&g_rp_mtx);
    snprintf(g_rp_pin, sizeof(g_rp_pin), "%s", pin);
    g_rp_state = RP_STATE_WAITING;
    g_rp_deadline = time(NULL) + RP_WAIT_SECONDS;
    g_rp_err[0] = 0;
    pthread_mutex_unlock(&g_rp_mtx);

    /* On-console notification so someone at the TV sees the PIN without
     * needing to look at the desktop app. */
    char notif_msg[128];
    snprintf(notif_msg, sizeof(notif_msg),
             "[ps5upload] Remote Play PIN: %s", pin);
    notif_send(notif_msg, NOTIF_LEVEL_INFO);

    return 0;
}

static int rp_get_status_locked(char *buf, size_t cap) {
    if (!buf || cap == 0) return -1;
    resolve_once();

    pthread_mutex_lock(&g_rp_mtx);
    int s = g_rp_state;

    /* If we're WAITING, probe for pairing completion. Prefer
     * ConfirmDeviceRegist (authoritative status codes + error reasons)
     * when available; fall back to connection/playing status polling. */
    if (s == RP_STATE_WAITING) {
        if (g_resolved && g_confirm_regist) {
            uint32_t status = 0, errcode = 0;
            if (g_confirm_regist(&status, &errcode) == 0) {
                if (status == 2) {
                    g_rp_state = RP_STATE_PAIRED;
                    s = RP_STATE_PAIRED;
                    notif_send("[ps5upload] Remote Play pairing successful",
                               NOTIF_LEVEL_INFO);
                } else if (status == 3 || status == 4) {
                    const char *reason =
                        errcode == 0x80FC1047u ? "invalid PIN" :
                        errcode == 0x80FC1040u ? "invalid account id" :
                        "failed";
                    g_rp_state = RP_STATE_FAILED;
                    s = RP_STATE_FAILED;
                    snprintf(g_rp_err, sizeof(g_rp_err),
                             "pairing %s (0x%08X)", reason, errcode);
                    char nmsg[160];
                    snprintf(nmsg, sizeof(nmsg),
                             "[ps5upload] Remote Play pairing %s", reason);
                    notif_send(nmsg, NOTIF_LEVEL_ERROR);
                }
            }
        }
        /* Fall back to connection-status polling if ConfirmDeviceRegist
         * is unavailable or returned a non-final status. */
        if (s == RP_STATE_WAITING && g_resolved && g_conn_status && g_is_playing) {
            int conn = g_conn_status();
            int playing = g_is_playing();
            if (conn != 0 || playing != 0) {
                g_rp_state = RP_STATE_PAIRED;
                s = RP_STATE_PAIRED;
            }
        }
        if (s == RP_STATE_WAITING && g_rp_deadline != 0) {
            if (time(NULL) >= g_rp_deadline) {
                g_rp_state = RP_STATE_TIMEOUT;
                s = RP_STATE_TIMEOUT;
                if (g_notify_pin_err) (void)g_notify_pin_err(1);
                notif_send("[ps5upload] Remote Play PIN timed out",
                           NOTIF_LEVEL_WARN);
            }
        }
    }

    int seconds_left = 0;
    if (s == RP_STATE_WAITING && g_rp_deadline != 0) {
        time_t now = time(NULL);
        if (now < g_rp_deadline) {
            seconds_left = (int)(g_rp_deadline - now);
        }
    }

    char err_esc[160];
    char pin_esc[32];
    char acct_esc[48];
    rp_json_escape(g_rp_err, err_esc, sizeof(err_esc));
    rp_json_escape(g_rp_pin, pin_esc, sizeof(pin_esc));
    rp_json_escape(g_rp_account_id, acct_esc, sizeof(acct_esc));
    int len = snprintf(buf, cap,
        "{\"state\":\"%s\",\"pin\":\"%s\",\"account_id\":\"%s\","
        "\"seconds_left\":%d,\"err\":\"%s\"}",
        state_name(s), pin_esc, acct_esc, seconds_left, err_esc);
    pthread_mutex_unlock(&g_rp_mtx);
    return len > 0 ? 0 : -1;
}

static int rp_cancel_locked(void) {
    resolve_once();
    pthread_mutex_lock(&g_rp_mtx);
    int s = g_rp_state;
    g_rp_state = RP_STATE_IDLE;
    g_rp_err[0] = 0;
    g_rp_pin[0] = 0;
    g_rp_deadline = 0;
    pthread_mutex_unlock(&g_rp_mtx);

    /* Disconnect any active session. Done outside the lock to avoid
     * holding the mutex over a Sony IPC round-trip. */
    if (s == RP_STATE_WAITING || s == RP_STATE_PAIRED) {
        if (g_resolved && g_disconnect) {
            (void)g_disconnect();
        }
    }
    return 0;
}

/* ── Sony-API serialization ──────────────────────────────────────────
 *
 * Every function below touches sceUserService, sceRegMgr or
 * sceRemoteplay. Those APIs are not safe to call concurrently from
 * multiple connection threads — the same hazard handle_profile_info,
 * register.c and bgft.c already serialize on `sony_api_lock`. The
 * Remote Play entry points were the one Sony-API surface in the
 * payload that did not, so a Profile-screen read racing the desktop's
 * Remote Play status poll could fault inside sceUserService and take
 * the host process down with it (console error CE-108262-9).
 *
 * The lock is held for a whole entry point rather than per call. That
 * is safe here because none of these block: there is no thread, no
 * sleep and no poll loop — pairing progresses through repeated short
 * `remoteplay_get_status` calls. Holding it across the network send
 * would be wrong, so the callers in runtime.c send AFTER these return.
 *
 * Thin wrappers, rather than lock/unlock inside each function, so that
 * the many early `return`s cannot leak the mutex. Internal cross-calls
 * go core-to-core (`rp_enable_locked` -> `rp_readiness_json_locked`);
 * `sony_api_lock` is not recursive, so calling a public wrapper from
 * inside another core would deadlock. */

int remoteplay_devices_json(char *out, size_t out_size) {
    pthread_mutex_lock(&sony_api_lock);
    int rc = rp_devices_json_locked(out, out_size);
    pthread_mutex_unlock(&sony_api_lock);
    return rc;
}

int remoteplay_enable(int user_scope, char *out, size_t out_size) {
    pthread_mutex_lock(&sony_api_lock);
    int rc = rp_enable_locked(user_scope, out, out_size);
    pthread_mutex_unlock(&sony_api_lock);
    return rc;
}

int remoteplay_readiness_json(char *out, size_t out_size) {
    pthread_mutex_lock(&sony_api_lock);
    int rc = rp_readiness_json_locked(out, out_size);
    pthread_mutex_unlock(&sony_api_lock);
    return rc;
}

int remoteplay_request(const char *manual_account_id) {
    pthread_mutex_lock(&sony_api_lock);
    int rc = rp_request_locked(manual_account_id);
    pthread_mutex_unlock(&sony_api_lock);
    return rc;
}

int remoteplay_get_status(char *buf, size_t cap) {
    pthread_mutex_lock(&sony_api_lock);
    int rc = rp_get_status_locked(buf, cap);
    pthread_mutex_unlock(&sony_api_lock);
    return rc;
}

int remoteplay_cancel(void) {
    pthread_mutex_lock(&sony_api_lock);
    int rc = rp_cancel_locked();
    pthread_mutex_unlock(&sony_api_lock);
    return rc;
}
