#include "remoteplay.h"

#include <ps5/kernel.h>

#include <dlfcn.h>
#include <pthread.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#include "notif.h"
#include "proc_list.h"
#include "sony_api_lock.h"
#include "sys_registry.h"
#include "rp_keys.h"
#include "rp_pair.h"
#include "fw_spoof.h"

/* Forward declaration: rp_enable_locked calls this before it is
 * defined. See the serialization note at the bottom of this file for
 * why the cores must call each other rather than the public wrappers. */
static int rp_readiness_json_locked(char *out, size_t out_size);

/* sceRemoteplayInitialize's "already initialised" return.
 *
 * Not from a Sony header — identified empirically, and the only code the
 * call ever returns on a second invocation within one payload's lifetime.
 * Treated as success, because it means the module is ready. */
#define RP_ERR_ALREADY_INITIALIZED ((int)0x80FC0003)

/* Registry key for the Remote Play enable flag. When this is 0, PINs
 * generated by sceRemoteplayGeneratePinCode are unusable — the PSN
 * pairing handshake silently fails because the service is off. elf-arsenal
 * force-sets it to 1 before generating a PIN; we do the same. */
#define SCE_REGMGR_ENT_KEY_REMOTEPLAY_rp_enable 1098973184u

/* libSceUserService — already link-time bound (-lSceUserService in the
 * Makefile) so a plain extern declaration is enough; dlsym(RTLD_DEFAULT)
 * resolves it at runtime. Same pattern as runtime.c line 9516. */
extern int sceUserServiceGetForegroundUser(int *user_id);
/* Every signed-in user, Sony-filled with -1 in the unused slots. Needed
 * because a console can have a user logged in with no user in the
 * foreground — see rp_resolve_account_slot(). */
extern int sceUserServiceGetLoginUserIdList(int *id_list);
#define RP_MAX_LOGIN_USERS 16
/* Must be called before any other user-service query, or
 * GetForegroundUser fails 0x80960002 even with a user logged in. Other
 * call sites in this tree already do it; Remote Play did not, which is
 * why it could never see the signed-in user. Idempotent. */
extern int sceUserServiceInitialize(void *params);

/* Idempotent wrapper so every entry point into this file is safe to call
 * without knowing whether something else initialised the service. */
static void rp_user_service_ready(void) {
    static int done = 0;
    if (done) return;
    (void)sceUserServiceInitialize(NULL);
    done = 1;
}

/* libSceRemoteplay function pointer types. The library is NOT link-time
 * bound (it's an optional SPRX; adding a DT_NEEDED entry would brick the
 * payload on firmwares where the module is absent), so we dlopen it once
 * and dlsym each symbol. NULL after resolve means "not available on this
 * firmware" — callers surface a clean error instead of crashing. */
/* Arity confirmed against three independent implementations (linkdev,
 * ps5-remoteplay-get-pin, ActRemoteLink) and verified on hardware: the
 * previous `(void)` declaration made every call fail 0x80FC0001, because
 * the callee read whatever happened to be in the argument registers.
 * That is why Remote Play never worked. */
typedef int (*rp_init_fn)(void *opt, size_t opt_size);
/* Writes the PIN through its ONLY argument. The previous
 * `(user_id, char*, size_t)` form passed an integer where the callee
 * performs a pointer store — a wild write, not a PIN. */
typedef int (*rp_gen_pin_fn)(uint32_t *out_pin);
/* The registration outcome for the live PIN (measured on a Fat at FW 13.60:
 * returns at once, status 0 while nobody has registered). The status values
 * rp_pair.h acts on are RP_CONFIRM_*. */
typedef int (*rp_confirm_regist_fn)(uint32_t *status, uint32_t *errcode);
/* Called with 1, makes the live PIN unusable: how a PIN is cancelled,
 * expired or replaced. */
typedef int (*rp_notify_pin_err_fn)(int errcode);

/* Not used, on purpose: sceRemoteplayGetConnectionStatus and
 * sceRemoteplayIsRemotePlaying. The old status poll called them with no
 * arguments as a "pairing done?" fallback; GetConnectionStatus then answered
 * 0x80FC0001 (bad argument) and any non-zero answer was read as "paired",
 * so every PIN showed as paired on the first poll (FW 13.60). A session
 * being up is not a registration anyway. sceRemoteplayDisconnect is not used
 * either: cancelling a PIN must not drop someone's running session. */

static rp_init_fn           g_init         = NULL;
static rp_gen_pin_fn        g_gen_pin      = NULL;
static rp_confirm_regist_fn g_confirm_regist = NULL;
static rp_notify_pin_err_fn g_notify_pin_err = NULL;

static pthread_once_t g_resolve_once = PTHREAD_ONCE_INIT;
static int g_resolved = 0;

static void resolve_impl(void) {
    /* libSceRemoteplay.sprx may live in several system paths depending
     * on firmware. Try each and stop at the first dlopen success, same
     * strategy as bgft.c's libSceBgft lookup. RTLD_GLOBAL so the symbols
     * are visible to subsequent dlsym(RTLD_DEFAULT) if needed. */
    static const char *const RP_LIB_PATHS[] = {
        "/system/common/lib/libSceRemoteplay.sprx",
        "/system_ex/common/lib/libSceRemoteplay.sprx",
        "/system/priv/lib/libSceRemoteplay.sprx",
    };
    void *lib = NULL;
    for (size_t i = 0; i < sizeof(RP_LIB_PATHS) / sizeof(RP_LIB_PATHS[0]); i++) {
        lib = dlopen(RP_LIB_PATHS[i], RTLD_NOW | RTLD_GLOBAL);
        if (lib) break;
    }
    if (!lib) {
        /* Fall back to RTLD_DEFAULT in case another process already
         * pulled the module into our address space. */
        lib = RTLD_DEFAULT;
    }
    g_init       = (rp_init_fn)dlsym(lib, "sceRemoteplayInitialize");
    g_gen_pin    = (rp_gen_pin_fn)dlsym(lib, "sceRemoteplayGeneratePinCode");
    g_confirm_regist = (rp_confirm_regist_fn)dlsym(lib, "sceRemoteplayConfirmDeviceRegist");
    g_notify_pin_err = (rp_notify_pin_err_fn)dlsym(lib, "sceRemoteplayNotifyPinCodeError");
    g_resolved = 1;
}

static void resolve_once(void) {
    pthread_once(&g_resolve_once, resolve_impl);
}

/* ── Account ID auto-detect via the registry ──────────────────────────
 *
 * Chiaki/pxplay need the console's PSN account ID (base64 of the 8-byte
 * raw id) in addition to the pairing PIN. Sony buries it; we read it
 * straight from the registry for the foreground user. Ported from
 * elf-arsenal's remoteplay.c, adapted to ps5upload's sys_registry
 * wrappers (dlsym'd sceRegMgr, read-only — no writes to the registry).
 *
 * The key IDs are computed with Sony's regmgr entry-number formula:
 * (slot-1)*stride + base, with a per-namespace base for the user-id and
 * account-id slot tables. These bases match ps5-payload-dev/regdump. */
static uint32_t rp_regmgr_ent_num(uint32_t slot, uint32_t max,
                                  uint32_t stride, uint32_t base,
                                  uint32_t fallback) {
    if (slot < 1 || slot > max) return fallback;
    return (slot - 1) * stride + base;
}

static uint32_t rp_key_user_id(uint32_t slot) {
    return rp_regmgr_ent_num(slot, 16, 65536, 125829376, 127140096);
}

static uint32_t rp_key_account_id(uint32_t slot) {
    return rp_regmgr_ent_num(slot, 16, 65536, 125830400, 127141120);
}

static const char rp_b64tab[] =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/* Standard base64 with '=' padding. Note: the elf-arsenal reference this
 * was ported from has a padding bug — its `i > inlen` guards can never
 * fire (i is capped at inlen by the read guards), so it emits trailing
 * 'A's instead of '=' and an 8-byte account id came out as
 * "…d4gA" instead of the correct "…d4g=". We drive padding off the
 * remaining-byte count of each group instead, which pads correctly for
 * all lengths (verified against RFC 4648 test vectors). */
static void rp_base64_encode(const uint8_t *in, size_t inlen, char *out) {
    size_t i = 0, j = 0;
    while (i < inlen) {
        size_t rem = inlen - i; /* bytes left in this group: 1, 2, or 3 */
        uint32_t o0 = in[i];
        uint32_t o1 = rem > 1 ? in[i + 1] : 0;
        uint32_t o2 = rem > 2 ? in[i + 2] : 0;
        uint32_t v = (o0 << 16) | (o1 << 8) | o2;
        out[j++] = rp_b64tab[(v >> 18) & 63];
        out[j++] = rp_b64tab[(v >> 12) & 63];
        out[j++] = rem > 1 ? rp_b64tab[(v >> 6) & 63] : '=';
        out[j++] = rem > 2 ? rp_b64tab[(v) & 63] : '=';
        i += 3;
    }
    out[j] = '\0';
}

/* Fill `out` with the foreground user's base64 account id, or leave it
 * an empty string if it can't be resolved (no user logged in, registry
 * symbols unavailable on this firmware, etc.). Never fails hard — a
 * missing account id just means the UI shows only the PIN. */
/* Registry slot (1..16) whose user-id matches `uid`, or -1.
 *
 * The slot is the index every per-user key is derived from, so almost
 * everything below needs it. */
static int rp_slot_for_user(int uid) {
    if (uid <= 0) return -1;
    for (uint32_t i = 1; i <= 16; i++) {
        int reg_uid = 0;
        if (sys_registry_get_int(rp_key_user_id(i), &reg_uid, NULL) == 0 &&
            reg_uid == uid) {
            return (int)i;
        }
    }
    return -1;
}

/* Does this slot hold an activated PSN account?
 *
 * An all-zero account id means the slot exists but was never activated —
 * a local-only user. Registration would be refused, so such a slot is no
 * better than no slot at all. */
static int rp_slot_has_account(int slot) {
    if (slot < 1) return 0;
    uint8_t raw[8] = {0};
    if (sys_registry_get_bin(rp_key_account_id((uint32_t)slot), raw,
                             sizeof(raw), NULL) != 0) {
        return 0;
    }
    for (size_t i = 0; i < sizeof(raw); i++) {
        if (raw[i]) return 1;
    }
    return 0;
}

/* The registry slot we should read the account id from, or -1.
 *
 * The foreground user is the right answer when there is one, but a
 * console can sit with a user signed in and nobody in the foreground:
 * measured on a PS5 Pro at FW 9.60 sitting on the dashboard, where
 * sceUserServiceGetForegroundUser SUCCEEDS and reports -1 while the
 * login list still contains the (activated) user. Asking only the
 * foreground made Remote Play look unavailable on a console that was
 * perfectly able to pair.
 *
 * So: prefer the foreground user, then fall back to the first signed-in
 * user with an activated account. `*via` reports which, because a
 * fallback is a guess on a multi-user console and the UI should be able
 * to say whose account it used rather than silently picking one. */
static int rp_resolve_account_slot(int *uid_out, const char **via) {
    if (uid_out) *uid_out = 0;
    if (via) *via = "none";
    rp_user_service_ready();

    int uid = 0;
    if (sceUserServiceGetForegroundUser(&uid) == 0 && uid > 0) {
        int slot = rp_slot_for_user(uid);
        if (slot > 0 && rp_slot_has_account(slot)) {
            if (uid_out) *uid_out = uid;
            if (via) *via = "foreground";
            return slot;
        }
    }

    int ids[RP_MAX_LOGIN_USERS];
    for (int i = 0; i < RP_MAX_LOGIN_USERS; i++) ids[i] = -1;
    if (sceUserServiceGetLoginUserIdList(ids) != 0) return -1;

    for (int i = 0; i < RP_MAX_LOGIN_USERS; i++) {
        if (ids[i] <= 0) continue; /* Sony pads with -1, not contiguously */
        int slot = rp_slot_for_user(ids[i]);
        if (slot > 0 && rp_slot_has_account(slot)) {
            if (uid_out) *uid_out = ids[i];
            if (via) *via = "login-list";
            return slot;
        }
    }
    return -1;
}

static void rp_get_account_id(char *out, size_t out_sz) {
    if (!out || out_sz == 0) return;
    out[0] = '\0';

    int slot = rp_resolve_account_slot(NULL, NULL);
    if (slot < 0) return;

    uint8_t raw[8] = {0};
    if (sys_registry_get_bin(rp_key_account_id((uint32_t)slot), raw,
                             sizeof(raw), NULL) != 0) {
        return;
    }

    char b64[16];
    rp_base64_encode(raw, sizeof(raw), b64);
    snprintf(out, out_sz, "%s", b64);
}

/* Turn Remote Play on.
 *
 * Two scopes, because FW 10.00 split them: the system-wide service
 * toggle, and per-user permission ("select which users can access your
 * console"). A console can have the service on while the account being
 * used is not permitted — pairing succeeds and every session is refused.
 *
 * Returns the re-read readiness snapshot rather than a bare ok, so the
 * caller never has to assume the write stuck.
 *
 * Return: >=0 length written, -1 write failed, -2 firmware has no
 * per-user setting, -3 no foreground user to apply it to. */
static int rp_enable_locked(int user_scope, char *out, size_t out_size) {
    unsigned int fw = fw_safe_kernel_version();

    if (!user_scope) {
        uint32_t ec = 0;
        if (sys_registry_set_int(rp_key_service_enable(), 1, &ec) != 0) {
            return -1;
        }
    } else {
        /* Refuse rather than write a key that may not exist on this
         * firmware. rp_fw_has_per_user_enable() also returns 0 when the
         * version could not be read at all, so an unidentified console
         * fails closed. */
        if (!rp_fw_has_per_user_enable(fw)) return -2;

        int uid = 0;
        rp_user_service_ready();
        if (sceUserServiceGetForegroundUser(&uid) != 0 || uid <= 0) return -3;
        int slot = rp_slot_for_user(uid);
        if (slot < 1) return -3;

        uint32_t ec = 0;
        if (sys_registry_set_int(rp_key_user_enable((uint32_t)slot), 1, &ec) != 0) {
            return -1;
        }
    }
    return rp_readiness_json_locked(out, out_size);
}

static void rp_json_escape(const char *src, char *dst, size_t dst_cap);

/* Read-only snapshot of everything that decides whether Remote Play can
 * work on this console, right now.
 *
 * Deliberately performs NO writes. The point is that the UI can tell
 * someone exactly which precondition is missing instead of surfacing a
 * Sony error code, and every fix is then a separate, explicit action.
 *
 * The two gates people trip over: the service toggle, and — on FW 10.00
 * and later — per-user permission. Pairing can succeed while sessions are
 * refused because the second is unset. */
static int rp_readiness_json_locked(char *out, size_t out_size) {
    /* Resolve first, or symbols_ok would report "unavailable" merely
     * because nothing has asked for them yet. Resolution is idempotent
     * and cheap; reporting a stale false is a lie the UI would repeat. */
    resolve_once();

    int uid = 0;
    int svc = 0;
    int usr = 0;
    unsigned int fw = fw_safe_kernel_version();
    int has_per_user = rp_fw_has_per_user_enable(fw);
    uint64_t acct_raw = 0;
    char acct_b64[32] = "";
    char acct_type[24] = "";
    char acct_type_esc[64] = "";

    /* Resolve exactly the way pairing will, or readiness would report a
     * console as unable to pair that pairing then succeeds on. `uid` is
     * the account we would actually use, which is NOT necessarily the
     * foreground one — that is reported separately and stays literal. */
    const char *acct_via = "none";
    int slot = rp_resolve_account_slot(&uid, &acct_via);
    int fg_uid = -1;
    if (sceUserServiceGetForegroundUser(&fg_uid) != 0) fg_uid = -1;

    if (slot > 0) {
        uint8_t raw[8] = {0};
        if (sys_registry_get_bin(rp_key_account_id((uint32_t)slot), raw,
                                 sizeof(raw), NULL) == 0) {
            /* Little-endian: the account id is the raw 8 bytes, and the
             * base64 clients want is over those bytes, not over a hex
             * rendering of them. */
            for (int i = 7; i >= 0; i--) {
                acct_raw = (acct_raw << 8) | raw[i];
            }
            rp_base64_encode(raw, sizeof(raw), acct_b64);
        }
        (void)sys_registry_get_str(rp_key_account_type((uint32_t)slot),
                                   acct_type, sizeof(acct_type), NULL);
    }

    /* Keep the registry error code. Passing NULL here is how a TOTAL
     * registry failure hid for so long: every read returned 0 and the
     * snapshot reported a perfectly plausible "nothing is enabled",
     * when in truth no read had succeeded at all. A non-zero
     * registry_err means "could not read", not "disabled". */
    uint32_t svc_ec = 0;
    (void)sys_registry_get_int(rp_key_service_enable(), &svc, &svc_ec);
    if (slot > 0 && has_per_user) {
        (void)sys_registry_get_int(rp_key_user_enable((uint32_t)slot), &usr,
                                   NULL);
    }

    rp_json_escape(acct_type, acct_type_esc, sizeof(acct_type_esc));

    return snprintf(out, out_size,
                    "{\"fw_magic\":%u,\"has_per_user\":%d,"
                    "\"foreground_uid\":%d,\"account_uid\":%d,"
                    "\"account_via\":\"%s\",\"user_slot\":%d,"
                    "\"account_id_b64\":\"%s\",\"account_id_raw\":%llu,"
                    "\"account_type\":\"%s\",\"service_enabled\":%d,"
                    "\"user_enabled\":%d,\"symbols_ok\":%d,\"registry_err\":%u}",
                    fw, has_per_user, fg_uid, uid, acct_via, slot, acct_b64,
                    (unsigned long long)acct_raw, acct_type_esc,
                    svc ? 1 : 0, usr ? 1 : 0, g_resolved ? 1 : 0, svc_ec);
}

static void rp_json_escape(const char *src, char *dst, size_t dst_cap) {
    if (!src || !dst || dst_cap == 0) return;
    size_t i = 0;
    while (*src && i + 2 < dst_cap) {
        char c = *src++;
        if (c == '"' || c == '\\') {
            dst[i++] = '\\';
            dst[i++] = c;
        } else if (c == '\n') {
            dst[i++] = '\\';
            dst[i++] = 'n';
        } else if ((unsigned char)c < 0x20) {
            continue;
        } else {
            dst[i++] = c;
        }
    }
    dst[i] = 0;
}

/* ── Pairing ─────────────────────────────────────────────────────────
 *
 * The state machine is rp_pair.c (pure, host-tested). This file supplies the
 * Sony calls it makes and the locking around them:
 *
 *   request, status  take sony_api_lock for the whole call, like every other
 *                    Remote Play entry point;
 *   cancel           flips the state to idle without any Sony lock, then
 *                    tries for the lock for a bounded time to invalidate the
 *                    PIN. If the lock is busy, the invalidation is owed and the
 *                    next status or request settles it. A cancel therefore
 *                    never waits on a Sony call.
 *
 * Pairing advances through status polls (no thread, no sleep loop): each
 * status call makes one ConfirmDeviceRegist probe. Nothing here kills or
 * restarts Sony's SceRemotePlay daemon: that froze a PS5 Pro on FW 9.60. */

static pthread_once_t g_pair_once = PTHREAD_ONCE_INIT;
static rp_pair_t g_pair;
/* The account id shown next to the PIN; set by a request. */
static pthread_mutex_t g_rp_acct_mtx = PTHREAD_MUTEX_INITIALIZER;
static char g_rp_account_id[32] = "";

/* How long a cancel waits for the Sony lock before leaving the PIN's
 * invalidation to the next status call. */
#define RP_CANCEL_LOCK_MS 1500

static void rp_pair_once(void) {
    rp_pair_init(&g_pair);
}

static int64_t rp_mono_ms(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (int64_t)ts.tv_sec * 1000 + ts.tv_nsec / 1000000;
}

/* Auto-enable the service before making a PIN: with rp_enable at 0 the PIN
 * is unusable and the registration fails without a reason. */
static void rp_ensure_enabled(void) {
    int enabled = 0;
    if (sys_registry_get_int(SCE_REGMGR_ENT_KEY_REMOTEPLAY_rp_enable,
                             &enabled, NULL) == 0 && enabled != 1) {
        sys_registry_set_int(SCE_REGMGR_ENT_KEY_REMOTEPLAY_rp_enable,
                             1, NULL);
    }
}

/* ── Sony calls for rp_pair (the caller holds sony_api_lock) ── */

static int rp_cb_prepare(void *ctx, char *err, size_t cap) {
    (void)ctx;
    resolve_once();
    if (!g_init || !g_gen_pin || !g_confirm_regist) {
        snprintf(err, cap, "this firmware does not expose sceRemoteplay to the payload");
        return -1;
    }
    rp_ensure_enabled();
    /* "Already initialised" (0x80FC0003) is what every call after the first
     * in a payload's lifetime returns, and it means ready. Treating it as
     * fatal made every pairing after the first fail until the payload was
     * re-sent (measured on a Pro at 9.60 and a Fat at 5.10). */
    int64_t t0 = rp_mono_ms();
    int rc = g_init(0, 0);
    fprintf(stderr, "[remoteplay] Initialize rc=0x%08X (%lld ms)\n", (unsigned)rc,
            (long long)(rp_mono_ms() - t0));
    if (rc == RP_ERR_ALREADY_INITIALIZED) rc = 0;
    if (rc != 0) {
        snprintf(err, cap, "sceRemoteplayInitialize failed: 0x%08X", (unsigned)rc);
        return -1;
    }
    /* A signed-in user with an activated account; not necessarily the
     * foreground one (a console on the dashboard has none, and pairs fine). */
    if (rp_resolve_account_slot(NULL, NULL) < 0) {
        snprintf(err, cap, "no signed-in user with an activated PSN account");
        return -1;
    }
    return 0;
}

static int rp_cb_gen_pin(void *ctx, uint32_t *pin) {
    (void)ctx;
    int64_t t0 = rp_mono_ms();
    int rc = g_gen_pin(pin);
    fprintf(stderr, "[remoteplay] GeneratePinCode rc=0x%08X (%lld ms)\n", (unsigned)rc,
            (long long)(rp_mono_ms() - t0));
    return rc;
}

static int rp_cb_confirm(void *ctx, uint32_t *status, uint32_t *errcode) {
    (void)ctx;
    /* Log only changes: the client polls every couple of seconds. */
    static int last_rc = -1;
    static uint32_t last_status = 0xFFFFFFFFu, last_err = 0xFFFFFFFFu;
    int64_t t0 = rp_mono_ms();
    int rc = g_confirm_regist(status, errcode);
    int64_t ms = rp_mono_ms() - t0;
    if (rc != last_rc || *status != last_status || *errcode != last_err || ms > 500) {
        fprintf(stderr, "[remoteplay] ConfirmDeviceRegist rc=0x%08X status=%u err=0x%08X (%lld ms)\n",
                (unsigned)rc, (unsigned)*status, (unsigned)*errcode, (long long)ms);
        last_rc = rc;
        last_status = *status;
        last_err = *errcode;
    }
    return rc;
}

static int rp_cb_invalidate(void *ctx) {
    (void)ctx;
    resolve_once();
    if (!g_notify_pin_err) return -1;
    int rc = g_notify_pin_err(1);
    fprintf(stderr, "[remoteplay] NotifyPinCodeError(1) rc=0x%08X\n", (unsigned)rc);
    return rc;
}

/* Is registration slot `slot` in use? Fills its user id and client type. */
static int rp_device_slot(uint32_t slot, int *user_id, int *client_type) {
    int uid = 0;
    uint32_t ec = 0;
    if (sys_registry_get_int(rp_key_regist_user_id(slot), &uid, &ec) != 0) return 0;
    if (uid == 0 || uid == -1) return 0;
    if (user_id) *user_id = uid;
    if (client_type) {
        *client_type = 0;
        (void)sys_registry_get_int(rp_key_regist_client_type(slot), client_type, NULL);
    }
    return 1;
}

static int rp_cb_device_count(void *ctx) {
    (void)ctx;
    int n = 0;
    for (uint32_t slot = 1; slot <= 32; slot++) n += rp_device_slot(slot, NULL, NULL);
    return n;
}

static void rp_cb_notify(void *ctx, const char *msg, int level) {
    (void)ctx;
    int lv = level == 2 ? NOTIF_LEVEL_ERROR : level == 1 ? NOTIF_LEVEL_WARN : NOTIF_LEVEL_INFO;
    fprintf(stderr, "[remoteplay] %s\n", msg);
    notif_send(msg, lv);
}

/* Every op. Only for callers that hold sony_api_lock. */
static rp_pair_ops_t rp_full_ops(void) {
    rp_pair_ops_t o;
    memset(&o, 0, sizeof(o));
    o.prepare = rp_cb_prepare;
    o.gen_pin = rp_cb_gen_pin;
    o.confirm = rp_cb_confirm;
    o.invalidate = rp_cb_invalidate;
    o.device_count = rp_cb_device_count;
    o.notify = rp_cb_notify;
    return o;
}

/* Only the invalidation, for a cancel that got the lock. */
static rp_pair_ops_t rp_settle_ops(void) {
    rp_pair_ops_t o;
    memset(&o, 0, sizeof(o));
    o.invalidate = rp_cb_invalidate;
    return o;
}

/* Take sony_api_lock if it frees up within `ms`; 1 = held. */
static int rp_sony_trylock_for(int ms) {
    int64_t until = rp_mono_ms() + ms;
    for (;;) {
        if (pthread_mutex_trylock(&sony_api_lock) == 0) return 1;
        if (rp_mono_ms() >= until) return 0;
        usleep(20 * 1000);
    }
}

static int rp_devices_json_locked(char *out, size_t out_size) {
    size_t n = 0;
    int first = 1;

    n += (size_t)snprintf(out + n, out_size - n, "{\"devices\":[");
    for (uint32_t slot = 1; slot <= 32; slot++) {
        int user_id = 0;
        int client_type = 0;
        if (!rp_device_slot(slot, &user_id, &client_type)) continue;
        /* Leave room for the closing "]}" plus a NUL. */
        if (n + 80 >= out_size) break;
        n += (size_t)snprintf(out + n, out_size - n,
                              "%s{\"slot\":%u,\"user_id\":%d,\"client_type\":%d}",
                              first ? "" : ",", slot, user_id, client_type);
        first = 0;
    }
    n += (size_t)snprintf(out + n, out_size - n, "]}");
    return (int)n;
}

void remoteplay_init(void) {
    pthread_once(&g_pair_once, rp_pair_once);
    (void)rp_pair_cancel(&g_pair);
    pthread_mutex_lock(&g_rp_acct_mtx);
    g_rp_account_id[0] = 0;
    pthread_mutex_unlock(&g_rp_acct_mtx);
}

static void rp_format_status(const rp_pair_view_t *v, char *buf, size_t cap) {
    char acct[sizeof(g_rp_account_id)];
    pthread_mutex_lock(&g_rp_acct_mtx);
    snprintf(acct, sizeof(acct), "%s", g_rp_account_id);
    pthread_mutex_unlock(&g_rp_acct_mtx);

    char err_esc[sizeof(v->err) * 2];
    char pin_esc[sizeof(v->pin) * 2];
    char acct_esc[sizeof(acct) * 2];
    rp_json_escape(v->err, err_esc, sizeof(err_esc));
    rp_json_escape(v->pin, pin_esc, sizeof(pin_esc));
    rp_json_escape(acct, acct_esc, sizeof(acct_esc));
    snprintf(buf, cap,
             "{\"state\":\"%s\",\"pin\":\"%s\",\"account_id\":\"%s\","
             "\"seconds_left\":%d,\"err\":\"%s\",\"probes\":%u,"
             "\"confirm_rc\":%u,\"confirm_status\":%u,\"confirm_err\":%u}",
             rp_pair_state_name(v->state), pin_esc, acct_esc, v->seconds_left,
             err_esc, (unsigned)v->probes, (unsigned)v->last_rc,
             (unsigned)v->last_status, (unsigned)v->last_err);
}

/* ── Public entry points ──────────────────────────────────────────────
 *
 * Every function below that touches sceUserService, sceRegMgr or
 * sceRemoteplay holds sony_api_lock for the whole call: those APIs are not
 * safe to call from several management workers at once (a Profile read
 * racing a Remote Play poll took the host process down, CE-108262-9). The
 * lock is not recursive, so cores call cores, never these wrappers. Callers
 * in runtime.c send their reply after these return. */

int remoteplay_devices_json(char *out, size_t out_size) {
    pthread_mutex_lock(&sony_api_lock);
    int rc = rp_devices_json_locked(out, out_size);
    pthread_mutex_unlock(&sony_api_lock);
    return rc;
}

int remoteplay_enable(int user_scope, char *out, size_t out_size) {
    pthread_mutex_lock(&sony_api_lock);
    int rc = rp_enable_locked(user_scope, out, out_size);
    pthread_mutex_unlock(&sony_api_lock);
    return rc;
}

int remoteplay_readiness_json(char *out, size_t out_size) {
    pthread_mutex_lock(&sony_api_lock);
    int rc = rp_readiness_json_locked(out, out_size);
    pthread_mutex_unlock(&sony_api_lock);
    return rc;
}

int remoteplay_pin_snapshot(char *out, size_t out_size) {
    if (!out || out_size == 0) return -1;
    pthread_once(&g_pair_once, rp_pair_once);
    rp_pair_view_t v;
    rp_pair_view(&g_pair, rp_mono_ms(), &v);
    char acct[sizeof(g_rp_account_id)];
    pthread_mutex_lock(&g_rp_acct_mtx);
    snprintf(acct, sizeof(acct), "%s", g_rp_account_id);
    pthread_mutex_unlock(&g_rp_acct_mtx);

    char pin_esc[sizeof(v.pin) * 2];
    char acct_esc[sizeof(acct) * 2];
    rp_json_escape(v.pin, pin_esc, sizeof(pin_esc));
    rp_json_escape(acct, acct_esc, sizeof(acct_esc));
    return snprintf(out, out_size, "{\"pin\":\"%s\",\"account_id\":\"%s\"}",
                    pin_esc, acct_esc);
}

int remoteplay_request(const char *manual_account_id) {
    pthread_once(&g_pair_once, rp_pair_once);
    pthread_mutex_lock(&sony_api_lock);
    /* A caller-supplied account id wins; otherwise the one pairing will use,
     * so the UI can show what Chiaki/pxplay need. */
    char account_id[sizeof(g_rp_account_id)] = "";
    if (manual_account_id && manual_account_id[0]) {
        snprintf(account_id, sizeof(account_id), "%s", manual_account_id);
    } else {
        rp_get_account_id(account_id, sizeof(account_id));
    }
    pthread_mutex_lock(&g_rp_acct_mtx);
    snprintf(g_rp_account_id, sizeof(g_rp_account_id), "%s", account_id);
    pthread_mutex_unlock(&g_rp_acct_mtx);

    rp_pair_ops_t ops = rp_full_ops();
    int rc = rp_pair_request(&g_pair, &ops, rp_mono_ms());
    pthread_mutex_unlock(&sony_api_lock);
    return rc;
}

int remoteplay_get_status(char *buf, size_t cap) {
    if (!buf || cap == 0) return -1;
    pthread_once(&g_pair_once, rp_pair_once);
    pthread_mutex_lock(&sony_api_lock);
    rp_pair_ops_t ops = rp_full_ops();
    (void)rp_pair_poll(&g_pair, &ops, rp_mono_ms());
    pthread_mutex_unlock(&sony_api_lock);

    rp_pair_view_t v;
    rp_pair_view(&g_pair, rp_mono_ms(), &v);
    rp_format_status(&v, buf, cap);
    return 0;
}

int remoteplay_cancel(void) {
    pthread_once(&g_pair_once, rp_pair_once);
    /* Idle first, with no Sony lock: the answer must not wait on a Sony call
     * another worker is inside. */
    if (!rp_pair_cancel(&g_pair)) return 0;
    if (rp_sony_trylock_for(RP_CANCEL_LOCK_MS)) {
        rp_pair_ops_t ops = rp_settle_ops();
        rp_pair_settle(&g_pair, &ops);
        pthread_mutex_unlock(&sony_api_lock);
    } else {
        fprintf(stderr, "[remoteplay] cancel: Sony lock busy, PIN invalidation left to the next poll\n");
    }
    return 0;
}
